"""initial

Revision ID: fab6c3c2d179
Revises: 
Create Date: 2024-11-24 20:17:25.177600+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab6c3c2d179'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_system',
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_system')),
    sa.UniqueConstraint('name', name=op.f('uq_payment_system_name'))
    )
    op.create_index('ix_payment_system_active_name', 'payment_system', ['active', 'name'], unique=False)
    op.create_index(op.f('ix_payment_system_id'), 'payment_system', ['id'], unique=False)
    op.create_table('tariff',
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('tariff_fee', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tariff')),
    sa.UniqueConstraint('name', name=op.f('uq_tariff_name'))
    )
    op.create_index('ix_tariff_active', 'tariff', ['active'], unique=False)
    op.create_index(op.f('ix_tariff_id'), 'tariff', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_tg_id', sa.String(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_user_tg_id'), 'user', ['user_tg_id'], unique=True)
    op.create_table('user_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_type')),
    sa.UniqueConstraint('name', name=op.f('uq_user_type_name'))
    )
    op.create_index(op.f('ix_user_type_id'), 'user_type', ['id'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_type_id', sa.Integer(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_profile_user_id_user')),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_type.id'], name=op.f('fk_user_profile_user_type_id_user_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile'))
    )
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=False)
    op.create_index('ix_user_profile_user_id_user_type_id', 'user_profile', ['user_id', 'user_type_id'], unique=False)
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('admin_bot_id', sa.Integer(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('payment_amount', sa.Integer(), server_default='250', nullable=False),
    sa.Column('payment_destination', sa.String(), server_default='', nullable=False),
    sa.Column('payment_system_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_bot_id'], ['user_profile.id'], name=op.f('fk_channel_admin_bot_id_user_profile')),
    sa.ForeignKeyConstraint(['owner_id'], ['user_profile.id'], name=op.f('fk_channel_owner_id_user_profile')),
    sa.ForeignKeyConstraint(['payment_system_id'], ['payment_system.id'], name=op.f('fk_channel_payment_system_id_payment_system')),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariff.id'], name=op.f('fk_channel_tariff_id_tariff')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel'))
    )
    op.create_index(op.f('ix_channel_id'), 'channel', ['id'], unique=False)
    op.create_index('ix_channel_owner_id_telegram_id', 'channel', ['owner_id', 'telegram_id'], unique=False)
    op.create_index(op.f('ix_channel_telegram_id'), 'channel', ['telegram_id'], unique=True)
    op.create_index('ix_channel_telegram_id_tariff_id', 'channel', ['telegram_id', 'tariff_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name=op.f('fk_payment_channel_id_channel')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_payment_user_id_user_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment'))
    )
    op.create_index(op.f('ix_payment_external_id'), 'payment', ['external_id'], unique=False)
    op.create_index(op.f('ix_payment_id'), 'payment', ['id'], unique=True)
    op.create_index('ix_payment_updated_at_channel_id_status', 'payment', ['updated_at', 'channel_id', 'status'], unique=False)
    op.create_index('ix_payment_user_id_channel_id', 'payment', ['user_id', 'channel_id'], unique=False)
    op.create_table('subscribe',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name=op.f('fk_subscribe_channel_id_channel')),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], name=op.f('fk_subscribe_user_profile_id_user_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscribe'))
    )
    op.create_index('ix_subscribe_channel_id_user_profile_id', 'subscribe', ['channel_id', 'user_profile_id'], unique=False)
    op.create_index(op.f('ix_subscribe_id'), 'subscribe', ['id'], unique=True)
    op.create_index('ix_subscribe_update_at_end_at', 'subscribe', ['update_at', 'end_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscribe_update_at_end_at', table_name='subscribe')
    op.drop_index(op.f('ix_subscribe_id'), table_name='subscribe')
    op.drop_index('ix_subscribe_channel_id_user_profile_id', table_name='subscribe')
    op.drop_table('subscribe')
    op.drop_index('ix_payment_user_id_channel_id', table_name='payment')
    op.drop_index('ix_payment_updated_at_channel_id_status', table_name='payment')
    op.drop_index(op.f('ix_payment_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_external_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index('ix_channel_telegram_id_tariff_id', table_name='channel')
    op.drop_index(op.f('ix_channel_telegram_id'), table_name='channel')
    op.drop_index('ix_channel_owner_id_telegram_id', table_name='channel')
    op.drop_index(op.f('ix_channel_id'), table_name='channel')
    op.drop_table('channel')
    op.drop_index('ix_user_profile_user_id_user_type_id', table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_user_type_id'), table_name='user_type')
    op.drop_table('user_type')
    op.drop_index(op.f('ix_user_user_tg_id'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tariff_id'), table_name='tariff')
    op.drop_index('ix_tariff_active', table_name='tariff')
    op.drop_table('tariff')
    op.drop_index(op.f('ix_payment_system_id'), table_name='payment_system')
    op.drop_index('ix_payment_system_active_name', table_name='payment_system')
    op.drop_table('payment_system')
    # ### end Alembic commands ###
