"""initial

Revision ID: 64a0ca0bfe3a
Revises: 
Create Date: 2025-01-22 17:48:06.930046+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64a0ca0bfe3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giga_tariff',
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('tariff_fee', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_giga_tariff')),
    sa.UniqueConstraint('name', name=op.f('uq_giga_tariff_name'))
    )
    op.create_index(op.f('ix_giga_tariff_id'), 'giga_tariff', ['id'], unique=False)
    op.create_index('ix_tariff_active', 'giga_tariff', ['active'], unique=False)
    op.create_table('payment_system',
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_system')),
    sa.UniqueConstraint('name', name=op.f('uq_payment_system_name'))
    )
    op.create_index('ix_payment_system_active_name', 'payment_system', ['active', 'name'], unique=False)
    op.create_index(op.f('ix_payment_system_id'), 'payment_system', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_tg_id', sa.String(), nullable=False),
    sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_user_tg_id'), 'user', ['user_tg_id'], unique=True)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_profile_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile'))
    )
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=False)
    op.create_index('ix_user_profile_user_id_user_type', 'user_profile', ['user_id', 'user_type'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('admin_bot_id', sa.Integer(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('payment_destination', sa.String(), server_default='', nullable=False),
    sa.Column('payment_system_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_bot_id'], ['user_profile.id'], name=op.f('fk_project_admin_bot_id_user_profile')),
    sa.ForeignKeyConstraint(['owner_id'], ['user_profile.id'], name=op.f('fk_project_owner_id_user_profile')),
    sa.ForeignKeyConstraint(['payment_system_id'], ['payment_system.id'], name=op.f('fk_project_payment_system_id_payment_system')),
    sa.ForeignKeyConstraint(['tariff_id'], ['giga_tariff.id'], name=op.f('fk_project_tariff_id_giga_tariff')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_index('ix_project_name_tariff_id', 'project', ['name', 'tariff_id'], unique=False)
    op.create_index('ix_project_owner_id_name', 'project', ['owner_id', 'name'], unique=False)
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_channel_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel'))
    )
    op.create_index(op.f('ix_channel_id'), 'channel', ['id'], unique=False)
    op.create_index(op.f('ix_channel_telegram_id'), 'channel', ['telegram_id'], unique=True)
    op.create_table('payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_payment_project_id_project')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_payment_user_id_user_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment'))
    )
    op.create_index(op.f('ix_payment_external_id'), 'payment', ['external_id'], unique=False)
    op.create_index(op.f('ix_payment_id'), 'payment', ['id'], unique=True)
    op.create_index('ix_payment_updated_at_project_id_status', 'payment', ['updated_at', 'project_id', 'status'], unique=False)
    op.create_index('ix_payment_user_id_project_id', 'payment', ['user_id', 'project_id'], unique=False)
    op.create_table('subscription',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_subscription_project_id_project')),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], name=op.f('fk_subscription_user_profile_id_user_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription'))
    )
    op.create_index('ix_subscribe_project_id_user_profile_id', 'subscription', ['project_id', 'user_profile_id'], unique=False)
    op.create_index('ix_subscribe_update_at_end_at', 'subscription', ['update_at', 'end_at'], unique=False)
    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=True)
    op.create_table('tariff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('payment_amount', sa.Integer(), server_default='250', nullable=False),
    sa.Column('subscribe_duration', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_tariff_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tariff'))
    )
    op.create_index('ix_project_id_tariff_active', 'tariff', ['project_id', 'active'], unique=False)
    op.create_index(op.f('ix_tariff_id'), 'tariff', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tariff_id'), table_name='tariff')
    op.drop_index('ix_project_id_tariff_active', table_name='tariff')
    op.drop_table('tariff')
    op.drop_index(op.f('ix_subscription_id'), table_name='subscription')
    op.drop_index('ix_subscribe_update_at_end_at', table_name='subscription')
    op.drop_index('ix_subscribe_project_id_user_profile_id', table_name='subscription')
    op.drop_table('subscription')
    op.drop_index('ix_payment_user_id_project_id', table_name='payment')
    op.drop_index('ix_payment_updated_at_project_id_status', table_name='payment')
    op.drop_index(op.f('ix_payment_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_external_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_channel_telegram_id'), table_name='channel')
    op.drop_index(op.f('ix_channel_id'), table_name='channel')
    op.drop_table('channel')
    op.drop_index('ix_project_owner_id_name', table_name='project')
    op.drop_index('ix_project_name_tariff_id', table_name='project')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_table('project')
    op.drop_index('ix_user_profile_user_id_user_type', table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_user_user_tg_id'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_payment_system_id'), table_name='payment_system')
    op.drop_index('ix_payment_system_active_name', table_name='payment_system')
    op.drop_table('payment_system')
    op.drop_index('ix_tariff_active', table_name='giga_tariff')
    op.drop_index(op.f('ix_giga_tariff_id'), table_name='giga_tariff')
    op.drop_table('giga_tariff')
    # ### end Alembic commands ###
